name: wardrobe
description: A new Flutter project.

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=3.1.3 <4.0.0"


dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  url_launcher: ^6.1.14
  flutter_svg: ^2.0.8
  flutter_rating_bar: ^4.0.1
  flutter_staggered_grid_view: ^0.7.0
  firebase_core: ^3.2.0
  firebase_database: ^11.0.3
  firebase_analytics: ^11.2.0
  google_sign_in: ^5.2.1
  cloud_firestore: ^5.1.0
  firebase_auth: ^5.1.2
  flutter_easyloading: ^3.0.5
  shared_preferences: ^2.2.2
  google_fonts: ^4.0.4
  provider: ^6.0.5
  image_picker: ^1.0.4
  dio: ^5.5.0+1
  firebase_storage: ^12.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^2.0.0


flutter:

  uses-material-design: true

  assets:
    - assets/images/

